# Generated by Django 3.0.4 on 2020-03-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aatooseetrii', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NatParks',
            new_name='NatPark',
        ),
    ]
